name: Tests

on:
  push:
    branches: ['main', 'starpc', 'grpc', 'drpc', 'twirp', 'grpc-npm']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['main', 'starpc', 'grpc', 'drpc', 'twirp', 'grpc-npm']

# Builds images for target boards.
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.20']
        node: [18.x]
    timeout-minutes: 10
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ matrix.go }}
      - name: Setup Node.JS ${{ matrix.node }}
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: npm install
        run: npm install --legacy-peer-deps
      - name: Typecheck
        run: npm run check
      - name: Build Javascript
        run: npm run build
      - name: Lint Javascript
        run: npm run lint:js
      - name: Test Js
        run: npm run test:js
      - name: Lint Go
        run: npm run lint:go
      - name: Test Go
        run: make test
